env:
  browser: true
  es6: true
  node: true
  jest: true
extends: "eslint:recommended"
parser: "babel-eslint"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  indent:
    - error
    - 2
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - error
    - argsIgnorePattern: ^_
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
plugins:
  - react
